[runtime]
workers = 10

[compression.default]
algorithm = "deflate"
level = 10
threshold = 64

[server]
listen = "0.0.0.0:6567"

name = "Neogrok 1.0/release"
magic = "insecure"

buffer = { read = 1024, per_client = 1024 }

[permissions.base.can]
create = { tcp = true, udp = false, http = false }
select = { tcp = false, udp = false, http = false }

[permissions.magic.can]
create = { tcp = true, udp = true, http = true }
select = { tcp = true, udp = true, http = true }
