[package]
name = "neogrok-compression"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libdeflate-sys = "0.11.0"
zstd-sys = { version = "2.0.4", default-features = false, features = [
    "thin",
    "std",
] }

neogrok-declmacro = { path = "../neogrok-declmacro" }
thiserror = { workspace = true }
