[package]
name = "zstd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zstd-sys = { version = "2.0.1", default-features = false, features = ["thin", "std"] }
